spring:
  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost:8081}/eureka

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_URL:localhost:9411}/api/v2/spans
